### ISSUE TITLE
transmission-daemon doesn't work with i2pd

### ISSUE THREAD

**Issue by paolomeraviglia** [l-n-s/transmission-i2p#2]
Hi

is the transmission-daemon working without the GTK application? I compiled the GTK version, configured it and started transmission-daemon specifying the right settings dir: it starts but from i2pd console I continuously reading BOB: Unknown command test.

I'm trying to download this:

http://tracker2.postman.i2p/index.php?action=Download&id=37408

Without success (It doesn't start: if I copy-paste the link inside the URL field, it doesn't download the torrent file to start downloading; if I first download it on my pc and then upload it, it appears on the list of web gui but doesn't start).

Everything seems to be configured well (http proxy is ok, i2pd is running ok, transmission-daemon is reacheable from web gui and answer)

All is running on RPI3

**Comment by l-n-s** [comment]
Couple of guys reported to successfully download torrents with daemon and i2pd.

> BOB: Unknown command test

This is known issue, there is discussion https://github.com/PurpleI2P/i2pd/issues/568

Need more details. Does GUI work as expected? Does transmission-daemon work with Java I2P? Any logs?

Unfortunately, I cannot help with the code, it's COMiX who wrote it. Your help with finding the cause will be very appreciated!

**Comment by faissaloo** [comment]
I am also facing this issue and am desperate for a fix. There should be no need to test with Java I2P since PurpleI2P/i2pd#568 have already tested it with Java I2P and confirmed that it works, they have pointed the issue out as being:  
>Basically last one is Transmission's bug, they send '\r\n' terminated address instead '\n\' as required by BOB protocol. Please let them know. I have placed the workaround in my code.  
  
https://github.com/PurpleI2P/i2pd/issues/568#issuecomment-234780032

**Comment by kayrus** [comment]
It fails when it tries to connect to the peer:

```
[18:57:06.089] _torrent_ Starting an OUTGOING connection with 7dmkk2id3dru6oylv3z2ipzfac6ssyu7zoehvfkbvmysuid4mv5q.b32.i2p (peer-mgr.c:4087)
```
